In [15]:
# 1. Low Pass Filtering
# memanggil modul yang diperlukan
import cv2
import numpy as np
from matplotlib import pyplot as plt

#bgr
img = cv2.imread('cat.png',0)
# membuat filter: matriks berukuran 5 x 5 

kernel = np.ones((5,5),np.float32)/25
print(kernel)

# lakukan filtering
img_lpf = cv2.filter2D(img,-1,kernel)

# menerapkan algoritma high-pass filtering:

# laplacian
laplacian = cv2.Laplacian(img,cv2.CV_64F)

# sobel dengan ukuran kernel 5
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=5)
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=5)


# Lakukan Thresholding

# Binary Threshold
ret,th1 = cv2.threshold(img,150,255,cv2.THRESH_BINARY)

# Adaptive Threshold dengan Mean
th2 = cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_MEAN_C,\
            cv2.THRESH_BINARY,11,2)

# Adaptive Threshold dengan Gaussian
th3 = cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\
            cv2.THRESH_BINARY,11,2)

# Plotting
plt.rcParams["figure.figsize"] = (100,50)
titles = ['Original', 'LPF', 'Laplacian', 'Sobel X', 'Sobel Y' , 'Global Thresholding (v = 150)',
            'Adaptive Mean Thresholding', 'Adaptive Gaussian Thresholding']
images = [img, img_lpf, laplacian, sobelx, sobely,th1, th2, th3]

# menampilkan hasil
for i in range(8):

    plt.subplot(2,8 , i+1) # Membuat subplot di baris pertama
    plt.imshow(images[i], cmap='gray')  # Mengubah colormap menjadi gray untuk gambar grayscale
    plt.title(titles[i])

    plt.subplot(2, 8, i+9) # Membuat subplot di baris kedua 
    plt.hist(images[i].ravel(), 256, [0, 256]) 
    plt.title(titles[i] + ' Histogram') 

# Menampilkan hasil subplot dan histogram yg dibuat 
plt.show()


[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
